(() => {
  const result=document.querySelector('#result'); if(!result) return;
  const style=document.createElement('style');style.textContent=`.v31-video{grid-column:1/-1}.v31-preview{width:100%;aspect-ratio:16/9;border-radius:18px;margin-top:12px;background:#08080c;object-fit:cover}.v31-options{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.v31-options label{display:flex;flex-direction:column;gap:6px}.v31-video .v14-row{margin-top:12px}@media(max-width:800px){.v31-video{grid-column:auto}.v31-options{grid-template-columns:1fr}}`;document.head.appendChild(style);
  const card=document.createElement('div');card.className='v14-card v31-video';card.innerHTML=`<span class="step">12</span><h3>🎬 YouTube Video Builder</h3><p>Turn your finished song and 16:9 cover into a YouTube-ready 1080p MP4 visualizer. The server encodes H.264 video + AAC audio.</p><div class="v31-options"><label>Video title<input id="videoTitle" maxlength="200" placeholder="Song title"></label><label>Artist / channel<input id="videoArtist" maxlength="80" value="Laxman Lofi"></label></div><div class="v31-options"><label><span>Show title on video</span><select id="videoOverlay"><option value="true">Yes</option><option value="false">No</option></select></label><label><span>Waveform visualizer</span><select id="videoWave"><option value="true">Yes</option><option value="false">No</option></select></label></div><div class="v14-row"><button id="videoBtn" class="v14-btn primary">Build 1080p MP4</button><a id="videoDownload" class="v14-btn hidden" download>Download MP4</a></div><div id="videoState" class="status offline">Generate a song and cover first</div><video id="videoPreview" class="v31-preview hidden" controls></video></div>`;
  result.appendChild(card);
  const $=id=>document.getElementById(id), api=()=>getApi();
  const sync=()=>{$('videoTitle').value=lastGeneration?.title||'';}; sync();
  $('videoBtn').onclick=async()=>{if(!lastGeneration?.outputId){alert('Generate a song first.');return}if(!lastGeneration.coverBase64){alert('Generate the AI cover first.');return}if(!api()){$('settingsDialog').showModal();return}const b=$('videoBtn');b.disabled=true;b.textContent='Rendering MP4…';$('videoState').textContent='Encoding 1080p video on the server…';$('videoState').className='status';try{const r=await fetch(`${api()}/video`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({output_id:lastGeneration.outputId,title:$('videoTitle').value.trim()||lastGeneration.title,cover_base64:lastGeneration.coverBase64,overlay_title:$('videoOverlay').value==='true',show_waveform:$('videoWave').value==='true'})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Video export failed');const url=`data:${d.mime_type};base64,${d.video_base64}`;$('videoPreview').src=url;$('videoPreview').classList.remove('hidden');$('videoDownload').href=url;$('videoDownload').download=`${safeFilename($('videoTitle').value||lastGeneration.title)}-Laxman-Lofi-1080p.mp4`;$('videoDownload').classList.remove('hidden');lastGeneration.video={fileName:d.file_name,codec:d.codec,width:d.width,height:d.height,youtubeReady:d.youtube_ready,createdAt:new Date().toISOString()};$('videoState').textContent='YouTube-ready MP4 created ✓';$('videoState').className='status online'}catch(e){$('videoState').textContent='Video export failed';$('videoState').className='status offline';alert(e.message)}finally{b.disabled=false;b.textContent='Build 1080p MP4'}};
})();
