(() => {
  const result=document.querySelector('#result'); if(!result) return;
  const style=document.createElement('style');style.textContent=`.v33-sync{grid-column:1/-1}.v33-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.v33-grid label{display:flex;flex-direction:column;gap:6px}.v33-segments{margin-top:14px;display:grid;gap:8px}.v33-seg{display:grid;grid-template-columns:80px 80px 1fr;gap:8px;align-items:center}.v33-seg input{min-width:0}.v33-badge{font-size:12px;padding:4px 8px;border-radius:999px;background:rgba(255,255,255,.08)}@media(max-width:800px){.v33-sync{grid-column:auto}.v33-grid{grid-template-columns:1fr}.v33-seg{grid-template-columns:70px 70px 1fr}}`;document.head.appendChild(style);
  const card=document.createElement('div');card.className='v14-card v33-sync';card.innerHTML=`<span class="step">15</span><h3>⏱️ Exact Lyric Sync Studio</h3><p>Use the generated vocal to create ASR-assisted lyric timestamps with faster-whisper. Matched lines use vocal timing; unmatched lines fall back to estimates. Review timing before export.</p><div class="v33-grid"><label>Whisper model<select id="timingModel"><option value="small" selected>Small · balanced</option><option value="medium">Medium · more accurate</option><option value="large-v3">Large v3 · highest accuracy</option></select></label><label>Language<select id="timingLanguage"><option value="auto">Auto detect</option><option value="ne">Nepali</option><option value="en">English</option><option value="hi">Hindi</option></select></label></div><div class="v14-row"><button id="timingBtn" class="v14-btn primary">Analyze Vocal Timing</button><button id="timingApply" class="v14-btn hidden">Apply Timing</button><span id="timingState" class="v33-badge">Generate a vocal song first</span></div><div id="timingSegments" class="v33-segments"></div>`;result.appendChild(card);
  const $=id=>document.getElementById(id), api=()=>getApi();
  $('timingBtn').onclick=async()=>{if(!lastGeneration?.outputId){alert('Generate a song first.');return}if(!api()){$('settingsDialog').showModal();return}const b=$('timingBtn');b.disabled=true;b.textContent='Analyzing vocal…';$('timingState').textContent='Separating/transcribing vocal with faster-whisper…';try{const r=await fetch(`${api()}/lyric-timing`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({output_id:lastGeneration.outputId,lyrics:$('lyrics')?.value||lastGeneration.lyrics||'',model_size:$('timingModel').value,language:$('timingLanguage').value==='auto'?null:$('timingLanguage').value})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Timing analysis failed');lastGeneration.lyricTiming=d;render(d.segments);$('timingState').textContent=`${d.asr_lines} ASR-matched · ${d.estimated_count} estimated · ${d.language}`;$('timingApply').classList.remove('hidden')}catch(e){$('timingState').textContent='Timing analysis failed';alert(e.message)}finally{b.disabled=false;b.textContent='Analyze Vocal Timing'}};
  function render(rows){const box=$('timingSegments');box.innerHTML=rows.map((x,i)=>`<div class="v33-seg"><input type="number" step="0.01" min="0" data-i="${i}" data-k="start" value="${x.start}"><input type="number" step="0.01" min="0" data-i="${i}" data-k="end" value="${x.end}"><input data-i="${i}" data-k="text" value="${String(x.text).replace(/"/g,'&quot;')}"></div>`).join('')}
  $('timingApply').onclick=()=>{if(!lastGeneration?.lyricTiming)return;document.querySelectorAll('.v33-seg input').forEach(el=>{const i=Number(el.dataset.i),k=el.dataset.k;if(k==='text')lastGeneration.lyricTiming.segments[i].text=el.value;else lastGeneration.lyricTiming.segments[i][k]=Number(el.value)});lastGeneration.lyricTiming.edited=true;$('timingState').textContent='Timing edits saved locally ✓'};
})();
