(() => {
  const result=document.querySelector('#result'); if(!result) return;
  const style=document.createElement('style');style.textContent=`.v36-mix{grid-column:1/-1}.v36-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.v36-control{padding:12px;border-radius:16px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.08)}.v36-control label{display:flex;justify-content:space-between;gap:8px;font-size:13px}.v36-control input{width:100%}.v36-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.v36-audio{width:100%;margin-top:12px}.v36-badge{display:inline-block;padding:5px 9px;border-radius:999px;background:rgba(74,222,128,.12);margin-left:8px;font-size:12px}@media(max-width:900px){.v36-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.v36-mix{grid-column:auto}.v36-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  const card=document.createElement('div');card.className='v14-card v36-mix';card.innerHTML=`<span class="step">17</span><h3>🎛️ AI Mix & Master Studio <span class="v36-badge">Automatic DSP</span></h3><p>Balance the separated vocal and instrumental stems, then apply cleanup, EQ, compression, de-essing-style control, stereo width and loudness mastering. Processing is deterministic FFmpeg DSP, not a generative model.</p><div class="v36-grid">
  ${[['vocalGain','Vocal level',100,0,200,1],['instGain','Instrumental level',100,0,200,1],['vocalPan','Vocal pan',0,-100,100,1],['cleanup','Vocal cleanup',35,0,100,1],['warmth','Warmth',25,-100,100,1],['presence','Presence',20,-100,100,1],['compression','Compression',35,0,100,1],['deessing','De-essing',20,0,100,1],['width','Stereo width',100,0,150,1],['lufs','Target LUFS',-14,-18,-9,1],['peak','True peak',-1,-3,-.1,.1]].map(([id,label,val,min,max,step])=>`<div class="v36-control"><label><span>${label}</span><b id="${id}Val">${val}</b></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${val}"></div>`).join('')}</div>
  <div class="v36-actions"><button id="mixBtn" class="v14-btn primary">Build Final Mix + Master</button><span id="mixState" class="status offline">Separate stems first</span></div><audio id="mixAudio" class="v36-audio" controls></audio><div id="mixResult" class="hint"></div><div class="v36-actions" id="mixDownloads"></div>`;result.appendChild(card);
  const ids=['vocalGain','instGain','vocalPan','cleanup','warmth','presence','compression','deessing','width','lufs','peak'];ids.forEach(id=>{const el=document.getElementById(id),v=document.getElementById(id+'Val');el.oninput=()=>v.textContent=el.value+(['vocalGain','instGain','cleanup','compression','deessing','width'].includes(id)?'%':'')});
  const $=id=>document.getElementById(id); const fmt=n=>Number(n).toFixed(1);
  $('mixBtn').onclick=async()=>{const id=lastGeneration?.outputId;if(!id){alert('Generate a song first.');return}const api=typeof getApi==='function'?getApi():'';if(!api){alert('Connect the Colab API endpoint first.');return} $('mixBtn').disabled=true;$('mixState').textContent='Building mix…';$('mixState').className='status';
    try{const body={output_id:id,vocal_gain:+$('vocalGain').value/100,instrumental_gain:+$('instGain').value/100,vocal_pan:+$('vocalPan').value/100,cleanup:+$('cleanup').value/100,warmth:+$('warmth').value/100,presence:+$('presence').value/100,compression:+$('compression').value/100,deessing:+$('deessing').value/100,stereo_width:+$('width').value/100,target_lufs:+$('lufs').value,true_peak:+$('peak').value};const r=await fetch(`${api}/mix-master`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Mix/master failed');
      const wav='data:audio/wav;base64,'+d.wav_base64,mp3='data:audio/mpeg;base64,'+d.mp3_base64;$('mixAudio').src=wav;$('mixResult').innerHTML=`Final master: ${d.sample_rate} Hz · ${d.wav_bit_depth}-bit WAV · ${d.mp3_bitrate} MP3 · target ${fmt(d.target_lufs)} LUFS / ${fmt(d.true_peak_target)} dBTP`;$('mixDownloads').innerHTML=`<a class="v14-btn" download="${id}-FINAL-MASTER.wav" href="${wav}">Download WAV</a><a class="v14-btn" download="${id}-FINAL-MASTER-320kbps.mp3" href="${mp3}">Download MP3</a>`;lastGeneration.mixMaster=d;$('mixState').textContent='Final master ready ✓';$('mixState').className='status online';
    }catch(e){$('mixState').textContent='Mix failed';$('mixState').className='status offline';alert(e.message)}finally{$('mixBtn').disabled=false}
  };
})();
