(() => {
 const result=document.querySelector('#result'); if(!result)return;
 const s=document.createElement('style');s.textContent=`.v38-card{grid-column:1/-1}.v38-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.v38-control{padding:12px;border-radius:16px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.08)}.v38-control label{display:flex;justify-content:space-between}.v38-control input{width:100%}.v38-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.v38-report{margin-top:14px;display:grid;gap:8px}.v38-section{padding:9px 12px;border-radius:12px;background:rgba(255,255,255,.04);display:flex;justify-content:space-between;gap:10px}.v38-audio{width:100%;margin-top:12px}@media(max-width:800px){.v38-grid{grid-template-columns:1fr}}`;document.head.appendChild(s);
 const c=document.createElement('div');c.className='v14-card v38-card';c.innerHTML=`<span class="step">19</span><h3>🎚️ Smart Arrangement & Dynamic Mix Studio</h3><p>Automatically inspect energy, trim accidental leading/trailing silence, add intelligent fades and apply a conservative chorus-energy lift. Processing is deterministic FFmpeg DSP; section labels are heuristic.</p><div class="v38-grid"><div class="v38-control"><label><span>Trim silence</span><input id="v38Trim" type="checkbox" checked></label></div><div class="v38-control"><label><span>Intro fade</span><b id="v38IntroVal">2.0s</b></label><input id="v38Intro" type="range" min="0" max="10" step="0.5" value="2"></div><div class="v38-control"><label><span>Outro fade</span><b id="v38OutroVal">3.0s</b></label><input id="v38Outro" type="range" min="0" max="10" step="0.5" value="3"></div><div class="v38-control"><label><span>Chorus lift</span><b id="v38LiftVal">8%</b></label><input id="v38Lift" type="range" min="0" max="30" value="8"></div><div class="v38-control"><label><span>Energy sensitivity</span><b id="v38SensVal">55%</b></label><input id="v38Sens" type="range" min="5" max="100" value="55"></div></div><div class="v38-actions"><button id="v38Analyze" class="v14-btn">Analyze sections</button><button id="v38Build" class="v14-btn primary">Smart Arrange</button><span id="v38State" class="status offline">Generate audio first</span></div><div id="v38Report" class="v38-report"></div><audio id="v38Audio" class="v38-audio" controls style="display:none"></audio><div id="v38Links" class="v38-actions"></div><p id="v38Note" class="hint"></p>`;result.appendChild(c);
 const $=id=>document.getElementById(id);$('v38Intro').oninput=()=>$('v38IntroVal').textContent=(+$('v38Intro').value).toFixed(1)+'s';$('v38Outro').oninput=()=>$('v38OutroVal').textContent=(+$('v38Outro').value).toFixed(1)+'s';$('v38Lift').oninput=()=>$('v38LiftVal').textContent=$('v38Lift').value+'%';$('v38Sens').oninput=()=>$('v38SensVal').textContent=$('v38Sens').value+'%';
 const request=()=>({output_id:lastGeneration?.outputId,trim_silence:$('v38Trim').checked,intro_fade:+$('v38Intro').value,outro_fade:+$('v38Outro').value,chorus_lift:+$('v38Lift').value/100,energy_sensitivity:+$('v38Sens').value/100});
 async function call(path,body){const api=typeof getApi==='function'?getApi():'';if(!api)throw new Error('Connect the Colab API endpoint first.');const r=await fetch(api+path,{method:'POST',headers:{'Content-Type':'application/json',...(typeof authHeaders==='function'?authHeaders():{})},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Arrangement request failed');return d;}
 function render(d){$('v38State').textContent='Analysis ready ✓';$('v38State').className='status online';const rows=(d.sections||[]).map(x=>`<div class="v38-section"><span><b>${x.label}</b> · ${x.start}s–${x.end}s</span><span>${x.energy_db} dB</span></div>`).join('');$('v38Report').innerHTML=`<div><b>Detected sections:</b> ${(d.sections||[]).length} · Threshold ${d.threshold_db??'—'} dB</div>${rows}`;$('v38Note').textContent=d.note||'';lastGeneration.arrangementAnalysis=d;}
 $('v38Analyze').onclick=async()=>{if(!lastGeneration?.outputId){alert('Generate audio first.');return}$('v38Analyze').disabled=true;$('v38State').textContent='Analyzing energy…';try{render(await call('/arrangement/analyze',request()))}catch(e){$('v38State').textContent='Analysis failed';alert(e.message)}finally{$('v38Analyze').disabled=false}};
 $('v38Build').onclick=async()=>{if(!lastGeneration?.outputId){alert('Generate audio first.');return}$('v38Build').disabled=true;$('v38State').textContent='Arranging + mastering…';try{const d=await call('/arrangement',request());const w='data:audio/wav;base64,'+d.wav_base64;$('v38Audio').src=w;$('v38Audio').style.display='block';$('v38Links').innerHTML=`<a class="v14-btn" href="${w}" download="${d.output_id}-SMART-ARRANGEMENT.wav">Download WAV</a><a class="v14-btn" href="data:audio/mpeg;base64,${d.mp3_base64}" download="${d.output_id}-SMART-ARRANGEMENT-320kbps.mp3">Download MP3</a>`;$('v38State').textContent='Smart arrangement ready ✓';$('v38State').className='status online';$('v38Note').textContent=d.note||'';lastGeneration.arrangement=d;}catch(e){$('v38State').textContent='Arrangement failed';alert(e.message)}finally{$('v38Build').disabled=false}};
 const next=document.createElement('script');next.src='v39.js';document.body.appendChild(next);
})();
