(() => {
  const result=document.querySelector('#result'); if(!result)return;
  const s=document.createElement('style');s.textContent=`.v39-card{grid-column:1/-1}.v39-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.v39-control{padding:12px;border-radius:16px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.08)}.v39-control label{display:flex;justify-content:space-between;gap:8px}.v39-control input,.v39-control select{min-width:0;width:100%;box-sizing:border-box}.v39-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.v39-timeline{display:grid;gap:8px;margin-top:14px}.v39-row{display:grid;grid-template-columns:92px 1fr 78px 78px;gap:8px;align-items:center;padding:10px;border-radius:13px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.06)}.v39-row input,.v39-row select{min-width:0;width:100%;box-sizing:border-box}.v39-meter{height:8px;border-radius:99px;background:rgba(255,255,255,.08);overflow:hidden}.v39-meter i{display:block;height:100%;background:currentColor;border-radius:99px}.v39-note{margin-top:12px}.v39-badge{font-size:11px;opacity:.8}@media(max-width:900px){.v39-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.v39-grid{grid-template-columns:1fr}.v39-row{grid-template-columns:1fr 1fr}.v39-row .v39-meter{grid-column:1/-1}}`;document.head.appendChild(s);
  const c=document.createElement('div');c.className='v14-card v39-card';c.innerHTML=`<span class="step">20</span><h3>🎼 AI Song Structure & Instrument Arrangement</h3><p>Turn the energy map into an editable song form: Intro → Verse → Pre-Chorus → Chorus → Bridge → Final Chorus → Outro. This version uses deterministic audio analysis and positional/repetition heuristics, not a generative music model.</p><div class="v39-grid"><div class="v39-control"><label><span>Structure mode</span></label><select id="v39Mode"><option value="balanced">Balanced</option><option value="lofi">Lofi / relaxed</option><option value="cinematic">Cinematic</option></select></div><div class="v39-control"><label><span>Chorus lift</span><b id="v39LiftVal">8%</b></label><input id="v39Lift" type="range" min="0" max="20" value="8"></div><div class="v39-control"><label><span>Bridge reduction</span><b id="v39BridgeVal">6%</b></label><input id="v39Bridge" type="range" min="0" max="20" value="6"></div><div class="v39-control"><label><span>Final chorus lift</span><b id="v39FinalVal">12%</b></label><input id="v39Final" type="range" min="0" max="25" value="12"></div></div><div class="v39-actions"><button id="v39Analyze" class="v14-btn">Analyze & Build Structure</button><button id="v39Apply" class="v14-btn primary">Apply Smart Structure</button><span id="v39State" class="status offline">Generate audio first</span></div><div id="v39Timeline" class="v39-timeline"></div><div class="v39-actions" id="v39Links"></div><p id="v39Note" class="hint v39-note"></p>`;result.appendChild(c);
  const $=id=>document.getElementById(id);const update=()=>{ $('v39LiftVal').textContent=$('v39Lift').value+'%';$('v39BridgeVal').textContent=$('v39Bridge').value+'%';$('v39FinalVal').textContent=$('v39Final').value+'%';};['v39Lift','v39Bridge','v39Final'].forEach(id=>$(id).oninput=update);
  const call=async(path,body)=>{const api=typeof getApi==='function'?getApi():'';if(!api)throw new Error('Connect the Colab API endpoint first.');const r=await fetch(api+path,{method:'POST',headers:{'Content-Type':'application/json',...(typeof authHeaders==='function'?authHeaders():{})},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Structure request failed');return d;};
  const labels=['intro','verse','pre-chorus','chorus','bridge','final chorus','outro'];
  function infer(analysis,mode){const src=(analysis?.sections||[]).filter(x=>x.end>x.start);if(!src.length)return[];const n=src.length;const out=[];src.forEach((x,i)=>{let label;if(i===0)label='intro';else if(i===n-1)label='outro';else if(mode==='cinematic'&&i===Math.max(1,Math.floor(n*.65)))label='bridge';else if(x.label==='chorus')label=i>n*.65?'final chorus':'chorus';else if(x.label==='build')label=(i===1||i===Math.floor(n/2))?'pre-chorus':'verse';else label='verse';out.push({...x,label,vocal:i===0||label==='intro'||label==='bridge'?'low':'active',instrumental:label==='intro'||label==='bridge'?'high':'medium'});});if(n>=5){const middle=Math.floor(n/2);if(out[middle].label==='verse')out[middle].label='bridge';}return out;}
  function render(){const rows=window.__laxmanStructure||[];$('v39Timeline').innerHTML=rows.map((x,i)=>{const pct=Math.max(5,Math.min(100,((x.energy_db+60)/60)*100));return `<div class="v39-row"><select data-i="${i}" class="v39-label">${labels.map(l=>`<option ${l===x.label?'selected':''}>${l}</option>`).join('')}</select><div><div><span class="v39-badge">${x.start}s–${x.end}s · ${x.vocal} vocal · ${x.instrumental} instrumental</span></div><div class="v39-meter"><i style="width:${pct}%"></i></div></div><span>${x.energy_db} dB</span><span>${x.vocal}</span></div>`}).join('');document.querySelectorAll('.v39-label').forEach(el=>el.onchange=()=>{window.__laxmanStructure[+el.dataset.i].label=el.value;});}
  function payload(){return{output_id:lastGeneration?.outputId,trim_silence:true,intro_fade:2,outro_fade:3,chorus_lift:+$('v39Lift').value/100,energy_sensitivity:.55};}
  $('v39Analyze').onclick=async()=>{if(!lastGeneration?.outputId){alert('Generate audio first.');return}$('v39Analyze').disabled=true;$('v39State').textContent='Reading energy structure…';try{const d=lastGeneration.arrangementAnalysis||await call('/arrangement/analyze',payload());lastGeneration.arrangementAnalysis=d;window.__laxmanStructure=infer(d,$('v39Mode').value);render();$('v39State').textContent='Editable structure ready ✓';$('v39State').className='status online';$('v39Note').textContent='Labels are inferred from energy, position and repetition. Edit any label before applying.';}catch(e){$('v39State').textContent='Structure analysis failed';alert(e.message)}finally{$('v39Analyze').disabled=false}};
  $('v39Mode').onchange=()=>{if(lastGeneration?.arrangementAnalysis){window.__laxmanStructure=infer(lastGeneration.arrangementAnalysis,$('v39Mode').value);render();}};
  $('v39Apply').onclick=async()=>{if(!lastGeneration?.outputId){alert('Generate audio first.');return}if(!window.__laxmanStructure?.length){$('v39Analyze').click();return}$('v39Apply').disabled=true;$('v39State').textContent='Applying section-aware mix…';try{const d=await call('/arrangement',{...payload(),chorus_lift:(+$('v39Lift').value/100)+(+$('v39Final').value/100),outro_fade:Math.max(3,+$('v39Bridge').value/2)});const w='data:audio/wav;base64,'+d.wav_base64;$('v39Links').innerHTML=`<audio controls style="width:100%" src="${w}"></audio><a class="v14-btn" href="${w}" download="${d.output_id}-STRUCTURED.wav">Download Structured WAV</a><a class="v14-btn" href="data:audio/mpeg;base64,${d.mp3_base64}" download="${d.output_id}-STRUCTURED-320kbps.mp3">Download Structured MP3</a>`;$('v39State').textContent='Smart structure applied ✓';$('v39State').className='status online';lastGeneration.structure={timeline:window.__laxmanStructure,mode:$('v39Mode').value,render:d};$('v39Note').textContent='Rendered with the current FFmpeg arrangement engine; the editable timeline is retained as release metadata.';}catch(e){$('v39State').textContent='Structure render failed';alert(e.message)}finally{$('v39Apply').disabled=false}};
  update();
  const next=document.createElement('script');next.src='v40.js';document.body.appendChild(next);
})();
