(() => {
  const result=document.querySelector('#result'); if(!result)return;
  const style=document.createElement('style');style.textContent=`.v41-card{grid-column:1/-1}.v41-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.v41-control{padding:12px;border-radius:16px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.08)}.v41-control label{display:flex;justify-content:space-between;gap:8px}.v41-control input,.v41-control select{width:100%;box-sizing:border-box}.v41-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.v41-timeline{display:grid;gap:9px;margin-top:14px}.v41-section{padding:12px;border-radius:15px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.07)}.v41-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.v41-meters{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.v41-meter{height:7px;border-radius:99px;background:rgba(255,255,255,.08);overflow:hidden}.v41-meter i{display:block;height:100%;background:currentColor;border-radius:99px}.v41-badges{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.v41-badge{font-size:11px;padding:4px 8px;border-radius:999px;background:rgba(255,255,255,.07)}.v41-note{margin-top:12px}@media(max-width:900px){.v41-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.v41-grid{grid-template-columns:1fr}.v41-meters{grid-template-columns:1fr}}`;document.head.appendChild(style);
  const card=document.createElement('div');card.className='v14-card v41-card';card.innerHTML=`<span class="step">22</span><h3>🎚️ V4.1 Stem-Aware Arrangement</h3><p>Process the real Demucs vocal and instrumental stems independently. V4.1 applies section-specific vocal/instrumental levels, chorus lifts, bridge reduction, vocal ducking and stereo width before a new 24-bit WAV + 320 kbps MP3 render.</p><div class="v41-grid"><div class="v41-control"><label><span>Vocal level</span><b id="v41VocalVal">100%</b></label><input id="v41Vocal" type="range" min="0" max="200" value="100"></div><div class="v41-control"><label><span>Instrumental level</span><b id="v41InstVal">100%</b></label><input id="v41Inst" type="range" min="0" max="200" value="100"></div><div class="v41-control"><label><span>Chorus vocal lift</span><b id="v41CVVal">8%</b></label><input id="v41CV" type="range" min="0" max="30" value="8"></div><div class="v41-control"><label><span>Chorus instrumental lift</span><b id="v41CIVal">10%</b></label><input id="v41CI" type="range" min="0" max="30" value="10"></div><div class="v41-control"><label><span>Bridge reduction</span><b id="v41BridgeVal">12%</b></label><input id="v41Bridge" type="range" min="0" max="60" value="12"></div><div class="v41-control"><label><span>Vocal ducking</span><b id="v41DuckVal">18%</b></label><input id="v41Duck" type="range" min="0" max="80" value="18"></div><div class="v41-control"><label><span>Stereo width</span><b id="v41WidthVal">105%</b></label><input id="v41Width" type="range" min="0" max="150" value="105"></div><div class="v41-control"><label><span>Target loudness</span><b id="v41LufsVal">-14 LUFS</b></label><input id="v41Lufs" type="range" min="-18" max="-9" value="-14"></div></div><div class="v41-actions"><button id="v41Analyze" class="v14-btn">Prepare & Analyze Stems</button><button id="v41Render" class="v14-btn primary">Render Stem Arrangement</button><span id="v41State" class="status offline">Generate audio first</span></div><div id="v41Timeline" class="v41-timeline"></div><div id="v41Links" class="v41-actions"></div><p id="v41Note" class="hint v41-note"></p>`;result.appendChild(card);
  const $=id=>document.getElementById(id);
  const sliderMap=[['v41Vocal','v41VocalVal','%'],['v41Inst','v41InstVal','%'],['v41CV','v41CVVal','%'],['v41CI','v41CIVal','%'],['v41Bridge','v41BridgeVal','%'],['v41Duck','v41DuckVal','%'],['v41Width','v41WidthVal','%']];
  sliderMap.forEach(([a,b,u])=>$(a).oninput=()=>$(b).textContent=$(a).value+u);$('v41Lufs').oninput=()=>$('v41LufsVal').textContent=$('v41Lufs').value+' LUFS';
  const api=()=>typeof getApi==='function'?getApi():'';const headers=()=>({ 'Content-Type':'application/json',...(typeof authHeaders==='function'?authHeaders():{}) });
  const call=async(path,body)=>{const base=api();if(!base)throw new Error('Connect the Colab API endpoint first.');const r=await fetch(base+path,{method:'POST',headers:headers(),body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'V4.1 request failed');return d;};
  function structure(){return window.__laxmanStructure||lastGeneration?.structure?.timeline||[];}
  function fallbackStructure(duration){const rows=structure();if(rows.length)return rows;return [{label:'intro',start:0,end:Math.min(20,duration)},{label:'verse',start:20,end:duration*.35},{label:'chorus',start:duration*.35,end:duration*.58},{label:'bridge',start:duration*.58,end:duration*.72},{label:'final chorus',start:duration*.72,end:duration*.92},{label:'outro',start:duration*.92,end:duration}];}
  function meter(v){return Math.max(4,Math.min(100,((Number(v)||-60)+60)/60*100));}
  function renderTimeline(d){const sections=d.sections||[];const vw=d.vocal_windows||[],iw=d.instrumental_windows||[];$('v41Timeline').innerHTML=sections.map((s,i)=>{const mid=(Number(s.start)+Number(s.end))/2;const near=a=>{const x=a.find(q=>mid>=Number(q.start)&&mid<=Number(q.end));return x?x.energy_db:-60};const ve=near(vw),ie=near(iw);return `<div class="v41-section"><div class="v41-head"><b>${s.label||'section'}</b><span>${Number(s.start).toFixed(1)}s → ${Number(s.end).toFixed(1)}s</span></div><div class="v41-meters"><div><small>Vocal energy · ${ve} dB</small><div class="v41-meter"><i style="width:${meter(ve)}%"></i></div></div><div><small>Instrumental energy · ${ie} dB</small><div class="v41-meter"><i style="width:${meter(ie)}%"></i></div></div></div><div class="v41-badges"><span class="v41-badge">Vocal ${Math.round((s.vocal_gain||1)*100)}%</span><span class="v41-badge">Instrumental ${Math.round((s.instrumental_gain||1)*100)}%</span></div></div>`}).join('');}
  function body(){return{output_id:lastGeneration?.outputId,structure:structure(),vocal_level:+$('v41Vocal').value/100,instrumental_level:+$('v41Inst').value/100,chorus_vocal_lift:+$('v41CV').value/100,chorus_instrumental_lift:+$('v41CI').value/100,bridge_reduction:+$('v41Bridge').value/100,ducking:+$('v41Duck').value/100,stereo_width:+$('v41Width').value/100,target_lufs:+$('v41Lufs').value,true_peak:-1};}
  $('v41Analyze').onclick=async()=>{if(!lastGeneration?.outputId){alert('Generate audio first.');return}$('v41Analyze').disabled=true;$('v41State').textContent='Checking Demucs stems…';try{let d;try{d=await call('/stem-arrangement/analyze',body());}catch(e){if(!/Separate vocals/i.test(e.message))throw e;$('v41State').textContent='Stems missing — running Demucs…';await call('/stems',{output_id:lastGeneration.outputId,model:'htdemucs'});d=await call('/stem-arrangement/analyze',body());}lastGeneration.v41StemAnalysis=d;renderTimeline(d);$('v41State').textContent='Stem analysis ready ✓';$('v41State').className='status online';$('v41Note').textContent='Vocal and instrumental energy are measured separately. Your reviewed V3.9 timeline is reused when available.';}catch(e){$('v41State').textContent='Analysis failed';alert(e.message)}finally{$('v41Analyze').disabled=false}};
  $('v41Render').onclick=async()=>{if(!lastGeneration?.outputId){alert('Generate audio first.');return}$('v41Render').disabled=true;$('v41State').textContent='Rendering stem-aware mix…';try{if(!lastGeneration.v41StemAnalysis)await $('v41Analyze').onclick();const d=await call('/stem-arrangement',body());const w='data:audio/wav;base64,'+d.wav_base64,m='data:audio/mpeg;base64,'+d.mp3_base64;$('v41Links').innerHTML=`<audio controls style="width:100%" src="${w}"></audio><a class="v14-btn" href="${w}" download="${safeFilename(lastGeneration.title)}-V41-STEM-AWARE.wav">Download V4.1 WAV</a><a class="v14-btn" href="${m}" download="${safeFilename(lastGeneration.title)}-V41-STEM-AWARE-320kbps.mp3">Download V4.1 MP3</a>`;$('v41State').textContent='V4.1 stem arrangement ready ✓';$('v41State').className='status online';lastGeneration.v41StemArrangement={...body(),result:d,createdAt:new Date().toISOString()};if(typeof updateHistoryRecord==='function')updateHistoryRecord({id:lastGeneration.id,v41StemArrangement:lastGeneration.v41StemArrangement});renderTimeline(d);$('v41Note').textContent='Rendered from the actual Demucs vocal + instrumental stems. Ducking is applied with FFmpeg sidechain compression; no new instruments or voices are synthesized.';}catch(e){$('v41State').textContent='Render failed';alert(e.message)}finally{$('v41Render').disabled=false}};
})();
