(() => {
  const result=document.querySelector('#result');if(!result)return;
  const style=document.createElement('style');style.textContent=`.v43-card{grid-column:1/-1}.v43-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.v43-stat{padding:16px;border-radius:18px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.08);text-align:center}.v43-stat b{display:block;font-size:25px;margin-top:5px}.v43-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.v43-gridline{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.v43-beat{padding:5px 8px;border-radius:999px;background:rgba(255,255,255,.07);font-size:11px}.v43-section{padding:12px;border-radius:15px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.07);display:flex;justify-content:space-between;gap:10px;align-items:center}.v43-list{display:grid;gap:8px;margin-top:12px}.v43-note{margin-top:12px}@media(max-width:900px){.v43-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.v43-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  const card=document.createElement('div');card.className='v14-card v43-card';card.innerHTML=`<span class="step">24</span><h3>🥁 V4.3 Beat & Tempo Intelligence</h3><p>Find an estimated BPM and beat grid from the generated audio, then snap your reviewed song sections to musical beat/bar boundaries before the next arrangement stage.</p><div class="v43-grid"><div class="v43-stat"><small>BPM</small><b id="v43Bpm">—</b></div><div class="v43-stat"><small>Beat</small><b id="v43Beat">—</b></div><div class="v43-stat"><small>Bars</small><b id="v43Bars">—</b></div><div class="v43-stat"><small>Confidence</small><b id="v43Conf">—</b></div></div><div class="v43-actions"><button id="v43Analyze" class="v14-btn primary">Analyze BPM & Beat Grid</button><button id="v43Snap" class="v14-btn">Snap Structure to Bars</button><button id="v43Copy" class="v14-btn">Copy Beat Map</button><span id="v43State" class="status offline">Generate audio first</span></div><div id="v43Beats" class="v43-gridline"></div><div id="v43Sections" class="v43-list"></div><p id="v43Note" class="hint v43-note"></p>`;result.appendChild(card);
  const $=id=>document.getElementById(id);const api=()=>typeof getApi==='function'?getApi():'';const headers=()=>({'Content-Type':'application/json',...(typeof authHeaders==='function'?authHeaders():{})});
  const structure=()=>window.__laxmanStructure||lastGeneration?.structure?.timeline||lastGeneration?.v42InstrumentAnalysis?.sections||[];
  function localBeat(buffer){const data=buffer.getChannelData(0),sr=buffer.sampleRate,hop=Math.max(1,Math.floor(sr*.02)),env=[];for(let i=0;i<data.length;i+=hop){let sum=0,n=Math.min(hop,data.length-i);for(let j=0;j<n;j++){const x=data[i+j];sum+=x*x}env.push(Math.sqrt(sum/n))}const sm=env.map((_,i)=>{let a=Math.max(0,i-5),b=i+1,s=0;for(let j=a;j<b;j++)s+=env[j];return s/(b-a)}),onset=[];for(let i=3;i<sm.length;i++)onset.push(Math.max(0,sm[i]-sm[i-3]));let best={bpm:90,score:-1};for(let bpm=55;bpm<=150;bpm++){const lag=Math.max(1,Math.round(60/bpm/.02));let score=0,n=0;for(let i=lag;i<onset.length;i+=Math.max(1,Math.floor(lag/2))){score+=onset[i]*onset[i-lag];n++}score/=Math.max(1,n);if(bpm>=65&&bpm<=95)score*=1.03;if(score>best.score)best={bpm,score}}const beat=60/best.bpm,duration=buffer.duration,first=Math.min(2,Math.max(0,duration-beat)),beats=[];for(let t=first;t<=duration;t+=beat)beats.push(+t.toFixed(3));return{bpm:best.bpm,beat_seconds:beat,duration,first_beat:first,beats,bar_starts:beats.filter((_,i)=>i%4===0),beats_per_bar:4,confidence:Math.min(1,Math.max(0,best.score*100)),method:'browser RMS onset-envelope heuristic'}}
  async function analyze(){if(!lastGeneration?.audioUrl)throw new Error('Generate audio first.');const base=api();if(base){try{const r=await fetch(base+'/beat/analyze',{method:'POST',headers:headers(),body:JSON.stringify({output_id:lastGeneration.outputId,structure:structure()})});if(r.ok)return await r.json()}catch(e){}}
    const ctx=new (window.AudioContext||window.webkitAudioContext)();const r=await fetch(lastGeneration.audioUrl);const b=await r.arrayBuffer();const buffer=await ctx.decodeAudioData(b);return localBeat(buffer)}
  function show(d){$('v43Bpm').textContent=Number(d.bpm).toFixed(1);$('v43Beat').textContent=Number(d.beat_seconds).toFixed(2)+'s';$('v43Bars').textContent=String(d.bar_starts?.length||0);$('v43Conf').textContent=Math.round((Number(d.confidence)||0)*100)+'%';$('v43Beats').innerHTML=(d.beats||[]).slice(0,32).map((t,i)=>`<span class="v43-beat">${i+1} · ${Number(t).toFixed(2)}s</span>`).join('');const secs=d.snapped_sections||structure();$('v43Sections').innerHTML=secs.map(s=>`<div class="v43-section"><b>${s.label||'section'}</b><span>${Number(s.start).toFixed(2)}s → ${Number(s.end).toFixed(2)}s ${s.beat_aligned?'✓':''}</span></div>`).join('');$('v43Note').textContent='BPM and beat positions are estimates from audio energy. The grid assumes 4/4 bars and should be reviewed against the waveform before release.';lastGeneration.v43BeatMap=d;if(typeof updateHistoryRecord==='function')updateHistoryRecord({id:lastGeneration.id,v43BeatMap:d})}
  $('v43Analyze').onclick=async()=>{$('v43Analyze').disabled=true;$('v43State').textContent='Analyzing rhythm…';try{const d=await analyze();show(d);$('v43State').textContent='Beat map ready ✓';$('v43State').className='status online'}catch(e){$('v43State').textContent='Analysis failed';alert(e.message)}finally{$('v43Analyze').disabled=false}};
  $('v43Snap').onclick=async()=>{if(!lastGeneration?.v43BeatMap)await $('v43Analyze').onclick();const d=lastGeneration?.v43BeatMap;if(!d)return;const secs=structure();const snap=t=>d.first_beat+Math.round((Number(t)-d.first_beat)/d.beat_seconds)*d.beat_seconds;const aligned=secs.map(s=>({...s,start:+Math.max(0,Math.min(d.duration,snap(s.start))).toFixed(3),end:+Math.max(0,Math.min(d.duration,snap(s.end))).toFixed(3),beat_aligned:true}));lastGeneration.v43BeatMap={...d,snapped_sections:aligned,section_alignment:'beat/bar grid'};window.__laxmanStructure=aligned;show(lastGeneration.v43BeatMap);if(lastGeneration.structure){lastGeneration.structure={...lastGeneration.structure,timeline:aligned,beatAligned:true}}if(typeof updateHistoryRecord==='function')updateHistoryRecord({id:lastGeneration.id,v43BeatMap:lastGeneration.v43BeatMap,structure:lastGeneration.structure});$('v43State').textContent='Structure snapped to beat grid ✓';$('v43State').className='status online'};
  $('v43Copy').onclick=async()=>{if(!lastGeneration?.v43BeatMap)await $('v43Analyze').onclick();const d=lastGeneration?.v43BeatMap;if(!d)return;await navigator.clipboard.writeText(JSON.stringify(d,null,2));$('v43State').textContent='Beat map copied ✓';};
})();